from .tss_file import TSSFile
import os
import json
from pathlib import Path
import csv
import numpy as np


def find_file(filename, search_dir):
    for root, dirs, files in os.walk(search_dir):
        if filename in files:
            return root
    return None


def glob_files(base_path, file_type):
    paths = Path(base_path).rglob(file_type)
    parent_folders = []
    file_names = []

    for p in paths:
        parent_folders.append(p.parent)
        file_names.append(p.name)

    return parent_folders, file_names


def _get_idx(time, xmin, xmax):
        xmin_idx = np.argmin(np.abs(time - xmin))
        xmax_idx = np.argmin(np.abs(time - xmax))
        return xmin_idx, xmax_idx


def multi_processor(input_folders, output_folder, output_name, comment_contains, username):
    headers_written = False
    csv_writer = None
    csv_file = None

    output_path = os.path.join(output_folder, output_name + '.csv')
    csv_file = open(output_path, mode="w", newline="", encoding="utf-8")

    from datetime import datetime
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    csv_file.write(f"# Generated Time: {current_time}\n")
    csv_file.write(f"# Generated By User: {username}\n")
    csv_file.write("# ------------------------------------------------\n")
    try:
        for input_folder in input_folders:
            json_folders, json_files = glob_files(input_folder, '*.json')
            for i in range(len(json_files)):
                json_file_path = os.path.join(json_folders[i], json_files[i])
                with open(json_file_path, 'r') as file:
                    json_data = json.load(file)
                time_stamp = json_files[i][3:18]
                tss_file = 'Tek' + time_stamp + '.tss'
                tss_folder = find_file(tss_file, json_folders[i])
                if tss_folder is None:
                    continue

                comment = json_data['comment']
                if comment_contains not in comment:
                    continue
                tss = TSSFile(tss_folder, tss_file)
                json_data['file'] = tss_file
                json_data['error'] = ''
                try:
                    time = tss.waveforms['ch1'].time_for_frame()*1e9
                    channel_labels = {value: key for key, value in tss.channel_labels.items()}
                    vgi = tss.waveforms[channel_labels['Vgi']].values_for_frame(0)
                    ig = tss.waveforms[channel_labels['Ig']].values_for_frame(0)
                    xmin_idx, xmax_idx = _get_idx(time, 100, 175)
                    vgi_measured = np.average(vgi[xmin_idx:xmax_idx])
                    ig_measured = np.average(ig[xmin_idx:xmax_idx])
                    json_data['Vgi_measured (V)'] = vgi_measured
                    json_data['Ig_measured (A)'] = ig_measured
                except Exception as e:
                    json_data['Vgi_measured (V)'] = ''
                    json_data['Ig_measured (A)'] = ''
                    json_data['error'] = str(e)

                if not headers_written:
                    # The column names will be the keys of the first element found
                    fieldnames = list(json_data.keys())
                    csv_writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
                    csv_writer.writeheader()
                    headers_written = True

                if csv_writer:
                    for record in [json_data]:
                        # extrasaction='ignore' ensures it won't crash if later files have extra keys
                        csv_writer.writerow(record)
                        print(f'{tss_file} processing is finished.')

    except Exception as e:
        print(f'Error occurred while processing {tss_file}: {e}')
        csv_file.close()
    finally:
        csv_file.close()


def multi_processor_vd_overshoot(input_folders, output_folder, output_name, comment_contains, username):
    from .wfm_edge import WFM_edge
    headers_written = False
    csv_writer = None
    csv_file = None

    output_path = os.path.join(output_folder, output_name + '.csv')
    csv_file = open(output_path, mode="w", newline="", encoding="utf-8")

    from datetime import datetime
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    csv_file.write(f"# Generated Time: {current_time}\n")
    csv_file.write(f"# Generated By User: {username}\n")
    csv_file.write("# ------------------------------------------------\n")
    try:
        for input_folder in input_folders:
            json_folders, json_files = glob_files(input_folder, '*.json')
            for i in range(len(json_files)):
                json_file_path = os.path.join(json_folders[i], json_files[i])
                with open(json_file_path, 'r') as file:
                    json_data = json.load(file)
                time_stamp = json_files[i][3:18]
                tss_file = 'Tek' + time_stamp + '.tss'
                tss_folder = find_file(tss_file, json_folders[i])
                if tss_folder is None:
                    continue

                comment = json_data['comment']
                if comment_contains not in comment:
                    continue
                tss = TSSFile(tss_folder, tss_file)
                json_data['file'] = tss_file
                json_data['error'] = ''
                try:
                    time = tss.waveforms['ch1'].time_for_frame()
                    channel_labels = {value: key for key, value in tss.channel_labels.items()}
                    vd = tss.waveforms[channel_labels['Vd']].values_for_frame(0)
                    vd_edges = WFM_edge(vd, time, falling_edge_number=2,
                                        rising_edge_number=2,
                                        peak_width=1,
                                        peak_distance=10,
                                        sigma=100,
                                        margin_ratio=20,)
                    t1 = vd_edges.get_edge(1, 'rising', 90)['time']
                    t2 = t1 + 100e-9
                    xmin_idx, xmax_idx = _get_idx(time, t1, t2)
                    vd_overshoot = max(vd[xmin_idx:xmax_idx])
                    json_data['Vd_overshoot (V)'] = vd_overshoot
                    #print(vd_overshoot)
                except Exception as e:
                    json_data['Vd_overshoot (V)'] = ''
                    json_data['error'] = str(e)

                if not headers_written:
                    # The column names will be the keys of the first element found
                    fieldnames = list(json_data.keys())
                    csv_writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
                    csv_writer.writeheader()
                    headers_written = True

                if csv_writer:
                    for record in [json_data]:
                        # extrasaction='ignore' ensures it won't crash if later files have extra keys
                        csv_writer.writerow(record)
                        print(f'{tss_file} processing is finished.')

    except Exception as e:
        print(f'Error occurred while processing {tss_file}: {e}')
        csv_file.close()
    finally:
        csv_file.close()
