from .tss_process import TSS_process
import os
import pandas as pd
import json
from pathlib import Path
import csv


def find_file(filename, search_dir):
    for root, dirs, files in os.walk(search_dir):
        if filename in files:
            return root
    return None


def glob_files(base_path, file_type):
    paths = Path(base_path).rglob(file_type)
    parent_folders = []
    file_names = []

    for p in paths:
        parent_folders.append(p.parent)
        file_names.append(p.name)

    return parent_folders, file_names


def single_processor(folder, tss_file, config_file, item='time', 
                     auto_deskew=False, manual_deskew=False, deskew_time=0, lshunt=None):

    path = find_file(tss_file, folder)
    tss = TSS_process(path, tss_file, config_file)
    if item == 'energy':
        energy_output = tss.energy_extraction(auto_deskew=auto_deskew, manual_deskew=manual_deskew, deskew_time=deskew_time, lshunt=lshunt)
        print(f"Eon (uJ): {energy_output[0]}, Eoff (uJ): {energy_output[1]}, Deskew time (ns): {energy_output[2]}, Lloop: {energy_output[3]}")
        tss.figure_before_deskew()
        tss.figure_time_deskew()
        tss.figure_on_IV()
        tss.figure_off_IV()
        tss.figure_on_energy()
        tss.figure_off_energy()
    elif item == 'time':
        time_output = tss.time_extraction()
        print(f"tdon (ns): {time_output[0]}, tf (ns): {time_output[1]}, tdoff (ns): {time_output[2]}, tr (ns): {time_output[3]}")
        tss.figure_on_off_VV()
    elif item == 'qg':
        qg = tss.gate_charge_extraction()
        print(f'Qg_ON (nC): {qg[1]}, Qg_OFF (nC): {qg[0]}')
        tss.figure_gate_waveform()
        tss.figure_qg()
    elif item == 'P42016':
        # dvdt = tss.dvdt_extraction()
        # print(f'dvdt_on (V/ns): {dvdt[0]}, dvdt_off (V/ns): {dvdt[2]}')
        didt = tss.P42016_extraction()
        print(f'didt_on (A/ns): {didt[0]}, didt_off (A/ns): {didt[1]}, is_at_mcgate-1.5 (A): {didt[2]}')
        # dvdt = tss.dvdt_extraction(plot_figures=True)
        didt = tss.P42016_extraction(plot_figures=True)
        dvdt = tss.P42016_vgi_extraction()
        print(f'dVgi/dt_on (V/ns): {dvdt[0]}, dVgi/dt_off (V/ns): {dvdt[1]}')
        dvdt = tss.P42016_vgi_extraction(plot_figures=True)


def multi_processor(input_folders, output_folder, output_name, comment_contains, config_file, parameters, username):
    version = '2.0'
    headers_written = False
    csv_writer = None
    csv_file = None

    output_path = os.path.join(output_folder, output_name + '.csv')
    csv_file = open(output_path, mode="w", newline="", encoding="utf-8")

    from datetime import datetime
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    csv_file.write(f"# Generated Time: {current_time}\n")
    csv_file.write(f"# Generated By User: {username}\n")
    csv_file.write(f"# Double pulse algorithm version: {version}\n")
    csv_file.write(f"# Config File: {config_file}\n")
    if parameters['energy']['flag']:
        csv_file.write(f"# Energy Extraction Parameters: auto_deskew={parameters['energy']['auto_deskew']}, manual_deskew={parameters['energy']['manual_deskew']}, deskew_time={parameters['energy']['deskew_time']}, lshunt={parameters['energy']['lshunt']}\n")
    if parameters['Rdson']['flag']:
        csv_file.write(f"# Rdson Extraction Parameters: t_trigger={parameters['Rdson']['t_trigger']}, t_avg={parameters['Rdson']['t_avg']}\n")
    csv_file.write("# ------------------------------------------------\n")
    try:
        for input_folder in input_folders:
            json_folders, json_files = glob_files(input_folder, '*.json')
            for i in range(len(json_files)):
                json_file_path = os.path.join(json_folders[i], json_files[i])
                with open(json_file_path, 'r') as file:
                    json_data = json.load(file)
                time_stamp = json_files[i][3:18]
                tss_file = 'Tek' + time_stamp + '.tss'
                tss_folder = find_file(tss_file, json_folders[i])
                if tss_folder is None:
                    continue

                comment = json_data['comment']
                if comment_contains not in comment:
                    continue
                tss = TSS_process(tss_folder, tss_file, config_file)
                json_data['file'] = tss_file
                json_data['error'] = ''
                if parameters['time']:
                    try:
                        time_output = tss.time_extraction()
                        json_data['tdon (ns)'] = time_output[0]
                        json_data['tf (ns)'] = time_output[1]
                        json_data['tdoff (ns)'] = time_output[2]
                        json_data['tr (ns)'] = time_output[3]
                    except Exception as e:
                        json_data['tdon (ns)'] = 0
                        json_data['tf (ns)'] = 0
                        json_data['tdoff (ns)'] = 0
                        json_data['tr (ns)'] = 0
                        json_data['error'] = 'error'
                if parameters['energy']['flag']:
                    try:
                        energy_output = tss.energy_extraction(auto_deskew=parameters['energy']['auto_deskew'], manual_deskew=parameters['energy']['manual_deskew'],
                                                            deskew_time=parameters['energy']['deskew_time'], lshunt=parameters['energy']['lshunt'])
                        json_data['Eon (uJ)'] = energy_output[0]
                        json_data['Eoff (uJ)'] = energy_output[1]
                    except Exception as e:
                        json_data['Eon (uJ)'] = 0
                        json_data['Eoff (uJ)'] = 0
                        json_data['error'] = 'error'
                if parameters['Qg']:
                    try:
                        qg_output = tss.gate_charge_extraction()
                        json_data['Qgoff (nC)'] = qg_output[0]
                        json_data['Qgon (nC)'] = qg_output[1]
                    except Exception as e:
                        json_data['Qgoff (nC)'] = 0
                        json_data['Qgon (nC)'] = 0
                        json_data['error'] = 'error'
                if parameters['Rdson']['flag']:
                    try:
                        inter_pulse_delay = json_data['inter_pulse_delay']
                        pulse2_width = json_data['pulse2_width']
                        dead_time = json_data['dead_time']
                        rdson_output = tss.rdson_extraction(t_trigger=parameters['Rdson']['t_trigger'], t_avg=parameters['Rdson']['t_avg'],
                                                        t_interpulse=inter_pulse_delay*1e-9,
                                                        t_dead=dead_time*1e-9,
                                                        t_2nd=pulse2_width*1e-9)
                        json_data['RDS_1st (mOhm)'] = rdson_output[0]
                        json_data['RDS_2nd (mOhm)'] = rdson_output[1]
                    except Exception as e:
                        json_data['RDS_1st (mOhm)'] = 0
                        json_data['RDS_2nd (mOhm)'] = 0
                        json_data['error'] = 'error'
                if parameters['dvdt']:
                    try:
                        dvdt_output = tss.dvdt_extraction()
                        json_data['Vd_dvdt_on_90_10 (V/ns)'] = dvdt_output[0]
                        json_data['Vd_dvdt_on_MAX (V/ns)'] = dvdt_output[1]
                        json_data['Vd_dvdt_off_10_90 (V/ns)'] = dvdt_output[2]
                        json_data['Vd_dvdt_off_MAX (V/ns)'] = dvdt_output[3]
                    except Exception as e:
                        json_data['Vd_dvdt_on_90_10 (V/ns)'] = 0
                        json_data['Vd_dvdt_on_MAX (V/ns)'] = 0
                        json_data['Vd_dvdt_off_10_90 (V/ns)'] = 0
                        json_data['Vd_dvdt_off_MAX (V/ns)'] = 0
                        json_data['error'] = 'error'

                if not headers_written:
                    # The column names will be the keys of the first element found
                    fieldnames = list(json_data.keys())
                    csv_writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
                    csv_writer.writeheader()
                    headers_written = True

                if csv_writer:
                    for record in [json_data]:
                        # extrasaction='ignore' ensures it won't crash if later files have extra keys
                        csv_writer.writerow(record)
                        print(f'{tss_file} processing is finished.')

    except Exception as e:
        print(f'Error occurred while processing {tss_file}: {e}')
        csv_file.close()
    finally:
        csv_file.close()


def multi_processor_no_json(input_folders, output_folder, output_name, config_file, parameters, username):
    version = '2.0'
    headers_written = False
    csv_writer = None
    csv_file = None

    output_path = os.path.join(output_folder, output_name + '.csv')
    csv_file = open(output_path, mode="w", newline="", encoding="utf-8")

    from datetime import datetime
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    csv_file.write(f"# Generated Time: {current_time}\n")
    csv_file.write(f"# Generated By User: {username}\n")
    csv_file.write(f"# Double pulse algorithm version: {version}\n")
    csv_file.write(f"# Config File: {config_file}\n")
    if parameters['energy']['flag']:
        csv_file.write(f"# Energy Extraction Parameters: auto_deskew={parameters['energy']['auto_deskew']}, manual_deskew={parameters['energy']['manual_deskew']}, deskew_time={parameters['energy']['deskew_time']}, lshunt={parameters['energy']['lshunt']}\n")
    if parameters['Rdson']['flag']:
        csv_file.write(f"# Rdson Extraction Parameters: t_trigger={parameters['Rdson']['t_trigger']}, t_avg={parameters['Rdson']['t_avg']}, inter_pulse_delay={parameters['Rdson']['inter_pulse_delay']}, pulse2_width={parameters['Rdson']['pulse2_width']}, dead_time={parameters['Rdson']['dead_time']}\n")
    csv_file.write("# ------------------------------------------------\n")
    try:
        for input_folder in input_folders:
            tss_folders, tss_files = glob_files(input_folder, '*.tss')
            for i in range(len(tss_files)):
                tss = TSS_process(tss_folders[i], tss_files[i], config_file)
                data = {'file': tss_files[i]}
                data['error'] = ''
                if parameters['time']:
                    try:
                        time_output = tss.time_extraction()
                        data['tdon (ns)'] = time_output[0]
                        data['tf (ns)'] = time_output[1]
                        data['tdoff (ns)'] = time_output[2]
                        data['tr (ns)'] = time_output[3]
                    except Exception as e:
                        data['tdon (ns)'] = 0
                        data['tf (ns)'] = 0
                        data['tdoff (ns)'] = 0
                        data['tr (ns)'] = 0
                        data['error'] = 'error'
                if parameters['energy']['flag']:
                    try:
                        energy_output = tss.energy_extraction(auto_deskew=parameters['energy']['auto_deskew'], manual_deskew=parameters['energy']['manual_deskew'],
                                                            deskew_time=parameters['energy']['deskew_time'], lshunt=parameters['energy']['lshunt'])
                        data['Eon (uJ)'] = energy_output[0]
                        data['Eoff (uJ)'] = energy_output[1]
                    except Exception as e:
                        data['Eon (uJ)'] = 0
                        data['Eoff (uJ)'] = 0
                        data['error'] = 'error'
                if parameters['Qg']:
                    try:
                        qg_output = tss.gate_charge_extraction()
                        data['Qgoff (nC)'] = qg_output[0]
                        data['Qgon (nC)'] = qg_output[1]
                    except Exception as e:
                        data['Qgoff (nC)'] = 0
                        data['Qgon (nC)'] = 0
                        data['error'] = 'error'
                if parameters['Rdson']['flag']:
                    try:
                        inter_pulse_delay = parameters['Rdson']['inter_pulse_delay']
                        pulse2_width = parameters['Rdson']['pulse2_width']
                        dead_time = parameters['Rdson']['dead_time']
                        rdson_output = tss.rdson_extraction(t_trigger=parameters['Rdson']['t_trigger'], t_avg=parameters['Rdson']['t_avg'],
                                                        t_interpulse=inter_pulse_delay*1e-9,
                                                        t_dead=dead_time*1e-9,
                                                        t_2nd=pulse2_width*1e-9)
                        data['RDS_1st (mOhm)'] = rdson_output[0]
                        data['RDS_2nd (mOhm)'] = rdson_output[1]
                    except Exception as e:
                        data['RDS_1st (mOhm)'] = 0
                        data['RDS_2nd (mOhm)'] = 0
                        data['error'] = 'error'
                if parameters['dvdt']:
                    try:
                        dvdt_output = tss.dvdt_extraction()
                        data['Vd_dvdt_on_90_10 (V/ns)'] = dvdt_output[0]
                        data['Vd_dvdt_on_MAX (V/ns)'] = dvdt_output[1]
                        data['Vd_dvdt_off_10_90 (V/ns)'] = dvdt_output[2]
                        data['Vd_dvdt_off_MAX (V/ns)'] = dvdt_output[3]
                    except Exception as e:
                        data['Vd_dvdt_on_90_10 (V/ns)'] = 0
                        data['Vd_dvdt_on_MAX (V/ns)'] = 0
                        data['Vd_dvdt_off_10_90 (V/ns)'] = 0
                        data['Vd_dvdt_off_MAX (V/ns)'] = 0
                        data['error'] = 'error'

                if not headers_written:
                    # The column names will be the keys of the first element found
                    fieldnames = list(data.keys())
                    csv_writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
                    csv_writer.writeheader()
                    headers_written = True

                if csv_writer:
                    for record in [data]:
                        # extrasaction='ignore' ensures it won't crash if later files have extra keys
                        csv_writer.writerow(record)
                        print(f'{tss_files[i]} processing is finished.')

    except Exception as e:
        print(f'Error occurred while processing {tss_files[i]}: {e}')
        csv_file.close()
    finally:
        csv_file.close()
